apiVersion: v1
kind: ServiceAccount
metadata:
  name: octagon-force-svc
  namespace: octagon-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: octagon-force-role
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "namespaces", "services"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: octagon-force-binding
subjects:
  - kind: ServiceAccount
    name: octagon-force-svc
    namespace: octagon-system
roleRef:
  kind: ClusterRole
  name: octagon-force-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: octagon-force-app
  name: octagon-force-app
  namespace: octagon-system
spec:
  selector:
    matchLabels:
      app: octagon-force-app
  template:
    metadata:
      labels:
        app: octagon-force-app
    spec:
      initContainers:
        - name: wait-for-bpf
          image: busybox:latest
          securityContext:
            privileged: true
          volumeMounts:
            - name: sys-fs-bpf
              mountPath: /sys/fs/bpf
              readOnly: true
              mountPropagation: HostToContainer # Crucial for seeing live host-side BPF mounts
          command:
            - sh
            - -c
            - |
              TARGET_DIR="/sys/fs/bpf/octagon_force"

              # Wait for directory to exist, then check if item count is > 1
              until [ -d "$TARGET_DIR" ] && [ $(ls -A "$TARGET_DIR" 2>/dev/null | wc -l) -gt 1 ]; do
                 echo "waiting for bpfs in $TARGET_DIR..."
                 sleep 2
              done
              echo "BPF maps detected! Starting container..."

      serviceAccountName: octagon-force-svc
      hostPID: true
      containers:
        - image: ghcr.io/ceald1/octagon-force-app:latest
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          name: octagon-force-app
          env:
            - name: LOKI_HOST
              value: "signoz-k8s-infra-otel-agent.monitoring.svc.cluster.local:3100"
            - name: TEMPO_HOST
              value: "signoz-otel-collector.monitoring.svc.cluster.local:4318"
          volumeMounts:
            # 1. BPF File System
            - name: sys-fs-bpf
              mountPath: /sys/fs/bpf
              #mountPropagation: Bidirectional
              mountPropagation: HostToContainer
            # 2. Host kernel debug/tracing system
            - name: sys-kernel-debug
              mountPath: /sys/kernel/debug
            # 3. Host Process filesystem (for monitoring process activity)
            - name: host-proc
              mountPath: /host/proc
              readOnly: true
            - name: file-system-monitor-override
              mountPath: /app/rules/file_system_monitor.yaml
              subPath: file_system_monitor.yaml
            - name: sigma-override
              mountPath: /app/rules/sigma.yaml
              subPath: sigma.yaml
      volumes:
        - name: sys-fs-bpf
          hostPath:
            path: /sys/fs/bpf
            type: DirectoryOrCreate

        - name: sys-kernel-debug
          hostPath:
            path: /sys/kernel/debug
            type: Directory
        - name: host-proc
          hostPath:
            path: /proc
            type: Directory
        - name: file-system-monitor-override
          configMap:
            name: file-system-monitor-override
        - name: sigma-override
          configMap:
            name: sigma-override
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: file-system-monitor-override
  namespace: octagon-system
data:
  file_system_monitor.yaml: |-
    rules:
      - rule:
        name: shadow deny
        action: "deny"
        filename: "/etc/shadow"
        message: "file: {{FileName}} was accessed by container ID: {{ContainerID}}"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sigma-override
  namespace: octagon-system
data:
  sigma.yaml: |-
    title: Curl ran
    id: a1b2c3d4-1111-2222-3333-444455556666
    status: experimental
    description: curl was ran!!
    detection:
      selection:
        Data|contains: "curl"
        Image|contains: "execve"
      condition: selection
    level: high
    ---
    title: Mount ran
    id: a1b2c3d4-1111-2222-3333-444455556667
    status: experimental
    description: mount was ran!!
    logsource:
      category: process_creation
      product: linux
    detection:
      selection_mount:
        Image: "execve"
        Data|contains: "mount"
      filter_umount:
        Data|contains: "umount"
      condition: selection_mount and not filter_umount
    level: high
