apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: octagon-force-bpf
  labels:
    app: octagon-force-bpf
spec:
  selector:
    matchLabels:
      app: octagon-force-bpf
  template:
    metadata:
      labels:
        app: octagon-force-bpf
    spec:
      hostPID: true
      containers:
        - name: octagon-force-bpf
          image: ghcr.io/ceald1/octagon-force-bpf:latest
          securityContext:
            privileged: true
          volumeMounts:
            - name: sys-fs-bpf
              mountPath: /sys/fs/bpf
              mountPropagation: Bidirectional
            - name: sys-kernel-tracing
              mountPath: /sys/kernel/tracing
            - name: sys-kernel-debug
              mountPath: /sys/kernel/debug
      volumes:
        - name: sys-fs-bpf
          hostPath:
            path: /sys/fs/bpf
            type: DirectoryOrCreate
        - name: sys-kernel-tracing
          hostPath:
            path: /sys/kernel/tracing
            type: DirectoryOrCreate
        - name: sys-kernel-debug
          hostPath:
            path: /sys/kernel/debug
            type: DirectoryOrCreate

#apiVersion: apps/v1
#kind: DaemonSet
#metadata:
#  labels:
#    app: octagon-force-bpf
#  name: octagon-force-bpf
#spec:
#  selector:
#    matchLabels:
#      app: octagon-force-bpf
#  template:
#    metadata:
#      labels:
#        app: octagon-force-bpf
#    spec:
#      containers:
#        - image: ghcr.io/ceald1/octagon-force-bpf:latest
#          securityContext:
#            privileged: true
#          name: octagon-force-bpf
#          volumeMounts:
#            - name: sys-fs-bpf
#              mountPath: /sys/fs/bpf
#      volumes:
#        - name: sys-fs-bpf
#          hostPath:
#            path: /sys/fs/bpf
#            type: DirectoryOrCreate
