// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package network

import (
	"structs"

	"github.com/cilium/ebpf"
)

type networkNetworkEnforcerRules struct {
	_      structs.HostLayout
	Name   [32]int8
	Host   [256]int8
	Action bool
}

type networkNetworkEvent struct {
	_           structs.HostLayout
	SourcePID   int32
	_           [4]byte
	ContainerID uint64
	Host        [256]int8
	Action      bool
	_           [7]byte
}

type networkProcKey struct {
	_         structs.HostLayout
	Pid       uint32
	_         [4]byte
	StartTime uint64
}
